name: Deploy to Streamlit Cloud
on:
  push:
    branches: [main]
    paths:
      - requirements2.txt
      - 'Trained_Models/**'
      - 'streamlit.py'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements2.txt

      - name: Deploy to Streamlit (placeholder)
        run: |
          echo "Streamlit Cloud automatically picks up changes on push — no manual deploy needed."
          streamlit run streamlit.py --server.headless true &
          sleep 5
